services:
  redis-container:
    image: docker.io/redis:7.2.4
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - demo-network
networks:
  demo-network:
    driver: bridge

#docker-compose -f ./deployment.yml up -d

#docker-compose -f ./deployment.yml down


#docker ps -a        lay tat ca cac container

#docker container prune    xoa container


#docker images kiểm tra tất cả các images có trên máy


#docker rmi idImage xóa 1 image có trên máy